import { OpenGymInst } from "../OpenGymInst";

const gyms = [
    //Sunday gyms
  new OpenGymInst(
    null,
    "Mt. Scott Community Center",
    "5530 Southeast 72nd Avenue",
    null,
    "Basketball",
    "Sunday",
    "2:30 - 4:30 PM",
    "$0 - $6.25",
    "All Ages",
    "https://www.portlandoregon.gov/parks/article/634572",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Sunday",
    "3:30 - 5:30 PM",
    "$1/Person",
    "Families (Ages 13 and under w/ Parent/Gaurdian)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "Mt. Scott Community Center",
    "5530 Southeast 72nd Avenue",
    null,
    "Basketball",
    "Sunday",
    "4:45 - 6:45 PM",
    "$0 - $6.25",
    "Ages 30+ (ID Required)",
    "https://www.portlandoregon.gov/parks/article/634572",
    null,
    null,
    null,
    null
  ),

  //Monday Gyms
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Monday",
    "6:00 - 8:00 AM",
    "Adults (18-59) $6.25, Seniors(60+) $5",
    "Open Adult (Ages 18+ w/ photo ID)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Monday",
    "2:45 - 5:00 PM",
    "Youth (3-12) $4.50, Teens (13-17) $5, Adults (18-59) $6.25",
    "Open Youth (Ages 8-20)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Monday",
    "6:00 - 8:00 PM",
    "Adults (18-59) $6.25, Seniors(60+) $5",
    "Ages 18+",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),

  //Tuesday gyms
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Tuesday",
    "6:00 - 8:00 AM",
    "Adults (18-59) $6.25, Seniors(60+) $5",
    "Open Adult (Ages 18+ w/ photo ID)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Tuesday",
    "8:00 - 10:00 AM",
    "Adults (18-59) $6.25, Seniors (60+) $5",
    "Ages 55+",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Tuesday",
    "2:45 - 5:00 PM",
    "Youth (3-12) $4.50, Teens (13-17) $5, Adults (18-59) $6.25",
    "Open Youth (Ages 8-20)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "Mt. Scott Community Center",
    "5530 Southeast 72nd Avenue",
    null,
    "Basketball",
    "Tuesday",
    "7:20 - 9:20 PM",
    "$0 - $6.25",
    "Ages 18+ (ID Required)",
    "https://www.portlandoregon.gov/parks/article/634572",
    null,
    null,
    null,
    null
  ),

  //Wednesday gyms
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Wednesday",
    "6:00 - 8:00 AM",
    "Adults (18-59) $6.25, Seniors(60+) $5",
    "Open Adult (Ages 18+ w/ photo ID)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Wednesday",
    "2:45 - 5:00 PM",
    "Youth (3-12) $4.50, Teens (13-17) $5, Adults (18-59) $6.25",
    "Open Youth (Ages 8-20)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),

  //Thursday gyms
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Thursday",
    "6:00 - 8:00 AM",
    "Adults (18-59) $6.25, Seniors(60+) $5",
    "Open Adult (Ages 18+ w/ photo ID)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Thursday",
    "8:00 - 10:00 AM",
    "Adults (18-59) $6.25, Seniors (60+) $5",
    "Ages 55+",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Thursday",
    "2:45 - 5:00 PM",
    "Youth (3-12) $4.50, Teens (13-17) $5, Adults (18-59) $6.25",
    "Open Youth (Ages 8-20)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "Mt. Scott Community Center",
    "5530 Southeast 72nd Avenue",
    null,
    "Basketball",
    "Thursday",
    "7:20 - 9:20 PM",
    "$0 - $6.25",
    "Ages 18+ (ID Required)",
    "https://www.portlandoregon.gov/parks/article/634572",
    null,
    null,
    null,
    null
  ),

  //Friday gyms
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Friday",
    "6:00 - 8:00 AM",
    "Adults (18-59) $6.25, Seniors(60+) $5",
    "Open Adult (Ages 18+ w/ photo ID)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Friday",
    "2:45 - 5:00 PM",
    "Youth (3-12) $4.50, Teens (13-17) $5, Adults (18-59) $6.25",
    "Open Youth (Ages 8-20)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Friday",
    "6:00 - 9:00 PM",
    "Youth (3-12) $4.50, Teens (13-17) $5, Adults (18-59) $6.25",
    "Open Youth (Ages 8-20)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  
  //Saturday gyms
  new OpenGymInst(
    null,
    "East Portland Community Center",
    "740 SE 106th Ave, Portland, OR 97216",
    null,
    "Basketball",
    "Saturday",
    "3:30 - 5:30 PM",
    "Adults (18-59) $6.25, Seniors(60+) $5",
    "Open Adult (Ages 18+ w/ photo ID)",
    "https://issuu.com/portlandparks/docs/epcc_wi_sp20_issuu?fr=sZGFiZjUwOTgxNw",
    null,
    null,
    null,
    null
  ),
  new OpenGymInst(
    null,
    "Mt. Scott Community Center",
    "5530 Southeast 72nd Avenue",
    null,
    "Basketball",
    "Saturday",
    "4:45 - 6:45 PM",
    "$0 - $6.25",
    "Ages 30+ (ID Required)",
    "https://www.portlandoregon.gov/parks/article/634572",
    null,
    null,
    null,
    null
  ),
];

export default gyms;